// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.IntExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.IntExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class IntExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsNullOrZero instead.")]
        public static bool IsNullOrZero(this int? value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsNullOrZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsZero instead.")]
        public static bool IsZero(this int value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsZero instead.")]
        public static bool IsZero(this int? value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessOrEqualZero instead.")]
        public static bool IsLessOrEqualZero(this int value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessOrEqualZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsGreaterThanOrEqualZero instead.")]
        public static bool IsGreaterThanOrEqualZero(this int value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsGreaterThanOrEqualZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsGreaterThanZero instead.")]
        public static bool IsGreaterThanZero(this int value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsGreaterThanZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.SetFlag instead.")]
        public static long SetFlag(this int value, int flag, bool set)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.SetFlag(value, flag, set);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsFlagSet instead.")]
        public static bool IsFlagSet(this int value, int flag)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsFlagSet(value, flag);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessZero instead.")]
        public static bool IsLessZero(this int value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessZero instead.")]
        public static bool IsLessZero(this int? value)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.IsLessZero(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.IntExtensions.GetExcelColumnName instead.")]
        public static string GetExcelColumnName(this int columnIndex)
            => global::RzR.Extensions.Domain.Primitives.IntExtensions.GetExcelColumnName(columnIndex);

    }
}
