// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.CommonExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Diagnostics.DocumentationExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class DocumentationExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation instead.")]
        public static XmlElement GetDocumentation(this MethodInfo methodInfo)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation(methodInfo);

        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation instead.")]
        public static XmlElement GetDocumentation(this MemberInfo memberInfo)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation(memberInfo);

        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetSummary instead.")]
        public static string GetSummary(this MemberInfo memberInfo)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetSummary(memberInfo);

        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation instead.")]
        public static XmlElement GetDocumentation(this Type type)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetDocumentation(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetSummary instead.")]
        public static string GetSummary(this Type type)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.GetSummary(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.XmlFromAssembly instead.")]
        public static XmlDocument XmlFromAssembly(this Assembly assembly)
            => global::RzR.Extensions.Domain.Diagnostics.DocumentationExtensions.XmlFromAssembly(assembly);

    }
}
