// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.TimeSpanExtension"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.TimeSpanExtension' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class TimeSpanExtension
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.Absolute instead.")]
        public static TimeSpan Absolute(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.Absolute(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsMissing instead.")]
        public static bool IsMissing(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsMissing(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsMissing instead.")]
        public static bool IsMissing(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsMissing(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.HasValidValue instead.")]
        public static bool HasValidValue(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.HasValidValue(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.HasValidValue instead.")]
        public static bool HasValidValue(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.HasValidValue(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsZero instead.")]
        public static bool IsZero(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsZero(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsZero instead.")]
        public static bool IsZero(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsZero(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsPositive instead.")]
        public static bool IsPositive(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsPositive(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsPositive instead.")]
        public static bool IsPositive(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsPositive(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsNegative instead.")]
        public static bool IsNegative(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsNegative(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsNegative instead.")]
        public static bool IsNegative(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsNegative(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsBetween instead.")]
        public static bool IsBetween(this TimeSpan source,
            TimeSpan minInclusive, TimeSpan maxInclusive)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsBetween(source, minInclusive, maxInclusive);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.DefaultIfNull instead.")]
        public static TimeSpan DefaultIfNull(this TimeSpan? source, TimeSpan defaultValue)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.DefaultIfNull(source, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ZeroIfNull instead.")]
        public static TimeSpan ZeroIfNull(this TimeSpan? source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ZeroIfNull(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.RoundUp instead.")]
        public static TimeSpan RoundUp(this TimeSpan source, TimeSpan interval)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.RoundUp(source, interval);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.RoundDown instead.")]
        public static TimeSpan RoundDown(this TimeSpan source, TimeSpan interval)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.RoundDown(source, interval);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.Clamp instead.")]
        public static TimeSpan Clamp(this TimeSpan source,
            TimeSpan min, TimeSpan max)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.Clamp(source, min, max);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalSecondsInt instead.")]
        public static int TotalSecondsInt(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalSecondsInt(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalMinutesInt instead.")]
        public static int TotalMinutesInt(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalMinutesInt(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalMillisecondsLong instead.")]
        public static long TotalMillisecondsLong(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.TotalMillisecondsLong(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ToClockFormat instead.")]
        public static string ToClockFormat(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ToClockFormat(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ToHumanReadable instead.")]
        public static string ToHumanReadable(this TimeSpan source)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ToHumanReadable(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ThrowIfMissing instead.")]
        public static void ThrowIfMissing(this TimeSpan source, string paramName = null)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ThrowIfMissing(source, paramName);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ThrowIfNegative instead.")]
        public static void ThrowIfNegative(this TimeSpan source, string paramName = null)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.ThrowIfNegative(source, paramName);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsShorterThan instead.")]
        public static bool IsShorterThan(this TimeSpan source, TimeSpan other)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsShorterThan(source, other);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsLongerThan instead.")]
        public static bool IsLongerThan(this TimeSpan source, TimeSpan other)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.IsLongerThan(source, other);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.AddSafe instead.")]
        public static TimeSpan AddSafe(this TimeSpan source, TimeSpan other)
            => global::RzR.Extensions.Domain.Primitives.TimeSpanExtension.AddSafe(source, other);

    }
}
