// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.Helpers
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class TinyEncryptionAlgorithmHelper
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.TeaEncrypt instead.")]
        public static void TeaEncrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.TeaEncrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.TeaDecrypt instead.")]
        public static void TeaDecrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.TeaDecrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XTeaEncrypt instead.")]
        public static void XTeaEncrypt(ref uint[] data, uint[] key, uint n = 32)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XTeaEncrypt(ref data, key, n);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XTeaDecrypt instead.")]
        public static void XTeaDecrypt(ref uint[] data, uint[] key, uint n = 32)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XTeaDecrypt(ref data, key, n);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.BlockTeaEncrypt instead.")]
        public static void BlockTeaEncrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.BlockTeaEncrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.BlockTeaDecrypt instead.")]
        public static void BlockTeaDecrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.BlockTeaDecrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XxTeaEncrypt instead.")]
        public static void XxTeaEncrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XxTeaEncrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XxTeaDecrypt instead.")]
        public static void XxTeaDecrypt(ref uint[] data, uint[] key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.XxTeaDecrypt(ref data, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.IsSameKey instead.")]
        public static bool IsSameKey(uint[] key1, uint[] key2)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.IsSameKey(key1, key2);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ConvertTextToData instead.")]
        public static void ConvertTextToData(ref string sourceText, ref uint[] data)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ConvertTextToData(ref sourceText, ref data);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ConvertDataToText instead.")]
        public static void ConvertDataToText(ref string sourceText, uint[] data)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ConvertDataToText(ref sourceText, data);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ReadData instead.")]
        public static void ReadData(ref string encryptedData, ref uint[] data)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.ReadData(ref encryptedData, ref data);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.WriteData instead.")]
        public static void WriteData(ref uint[] encryptedData, ref string resultData)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.WriteData(ref encryptedData, ref resultData);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.GeneratePassKeyFromPassCode instead.")]
        public static string GeneratePassKeyFromPassCode(string passCode, out uint[] passKey)
            => global::RzR.Extensions.Domain.Cryptography.Tea.TinyEncryptionAlgorithmHelper.GeneratePassKeyFromPassCode(passCode, out passKey);

    }
}
