// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.ByteExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.ByteExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class ByteExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToBase64String instead.")]
        public static string ToBase64String(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToBase64String(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetHashSha256String instead.")]
        public static string GetHashSha256String(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetHashSha256String(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToHexString instead.")]
        public static string ToHexString(this byte[] bytes, bool upperCase = false)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToHexString(bytes, upperCase);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.Sha256Hex instead.")]
        public static string Sha256Hex(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.Sha256Hex(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetHashSha1String instead.")]
        public static string GetHashSha1String(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetHashSha1String(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetStringUTF8 instead.")]
        public static string GetStringUTF8(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetStringUTF8(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetString instead.")]
        public static string GetString(this byte[] bytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.GetString(bytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToStringFromByteUnicode instead.")]
        public static string ToStringFromByteUnicode(this byte[] input)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToStringFromByteUnicode(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToHexByte instead.")]
        public static string ToHexByte(this byte[] clearText, bool withSpace = false)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.ToHexByte(clearText, withSpace);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.CompareTo instead.")]
        public static bool CompareTo(this byte[] a, byte[] b)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.CompareTo(a, b);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.GZipCompress instead.")]
        public static byte[] GZipCompress(this byte[] source, CompressionLevel compressionLevel)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.GZipCompress(source, compressionLevel);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.Base32BytesToString instead.")]
        public static string Base32BytesToString(this byte[] sourceBytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.Base32BytesToString(sourceBytes);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ByteExtensions.IsEntirelyNull instead.")]
        public static bool IsEntirelyNull(this byte[] sourceBytes)
            => global::RzR.Extensions.Domain.Primitives.ByteExtensions.IsEntirelyNull(sourceBytes);

    }
}
