// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.ArraysExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Collections.EnumerableExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Collections.EnumerableExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class EnumerableExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Replace instead.")]
        public static IEnumerable<T> Replace<T>(this IEnumerable<T> enumerable, int index, T value)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Replace<T>(enumerable, index, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Join instead.")]
        public static string Join(this IEnumerable<string> source, string separator)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Join(source, separator);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast instead.")]
        public static bool IsLast<T>(this IEnumerable<T> items, T item)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast<T>(items, item);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsFirst instead.")]
        public static bool IsFirst<T>(this IEnumerable<T> items, T item)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsFirst<T>(items, item);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDifferences instead.")]
        public static (IList<TItem>, IList<TItem>) GetDifferences<TItem>(this IEnumerable<TItem> source,
            IEnumerable<TItem> target)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDifferences<TItem>(source, target);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ContainsAny instead.")]
        public static bool ContainsAny<TSource>(this IEnumerable<TSource> source, IEnumerable<TSource> target)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ContainsAny<TSource>(source, target);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AnyStartWith instead.")]
        public static bool AnyStartWith(this IEnumerable<string> source, IEnumerable<string> target)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AnyStartWith(source, target);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AnyStartWith instead.")]
        public static bool AnyStartWith(this IEnumerable<string> source, string target)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AnyStartWith(source, target);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToObservableCollection instead.")]
        public static ObservableCollection<T> ToObservableCollection<T>(this IEnumerable<T> coll)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToObservableCollection<T>(coll);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Randomize instead.")]
        public static IEnumerable<T> Randomize<T>(this IEnumerable<T> target)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Randomize<T>(target);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Transpose instead.")]
        public static IEnumerable<IEnumerable<T>> Transpose<T>(this IEnumerable<IEnumerable<T>> collection)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Transpose<T>(collection);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToCollection instead.")]
        public static Collection<T> ToCollection<T>(this IEnumerable<T> enumerable)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToCollection<T>(enumerable);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Combinations instead.")]
        public static IEnumerable<IEnumerable<T>> Combinations<T>(this IEnumerable<T> source, int select,
            bool repetition = false)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Combinations<T>(source, select, repetition);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToDataTable instead.")]
        public static DataTable ToDataTable<T>(this IEnumerable<T> data)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToDataTable<T>(data);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToDataTableDynamic instead.")]
        public static DataTable ToDataTableDynamic<T>(this IEnumerable<T> data)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToDataTableDynamic<T>(data);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsNullOrEmptyEnumerable instead.")]
        public static bool IsNullOrEmptyEnumerable<T>(this IEnumerable<T> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsNullOrEmptyEnumerable<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsNotNullOrEmptyEnumerable instead.")]
        public static bool IsNotNullOrEmptyEnumerable<T>(this IEnumerable<T> enumerable)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsNotNullOrEmptyEnumerable<T>(enumerable);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.WithIndex instead.")]
        public static IEnumerable<(T item, int index)> WithIndex<T>(this IEnumerable<T> self)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.WithIndex<T>(self);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.WithIndexModel instead.")]
        public static IEnumerable<WithIndexModel<T>> WithIndexModel<T>(this IEnumerable<T> self)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.WithIndexModel<T>(self);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ListToString instead.")]
        public static string ListToString<T>(this IEnumerable<T> list, string delimiter)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ListToString<T>(list, delimiter);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.CloneCollection instead.")]
        public static IEnumerable<T> CloneCollection<T>(this IEnumerable<T> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.CloneCollection<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.NotNull instead.")]
        public static IEnumerable<T> NotNull<T>(this IEnumerable<T> list)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.NotNull<T>(list);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ActionForEach instead.")]
        public static void ActionForEach<T>(this IEnumerable<T> source, Action<T> action)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ActionForEach<T>(source, action);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToSpaceSeparatedString instead.")]
        public static string ToSpaceSeparatedString(this IEnumerable<string> list)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToSpaceSeparatedString(list);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.HasDuplicates instead.")]
        public static bool HasDuplicates<T, TProp>(this IEnumerable<T> list, Func<T, TProp> selector)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.HasDuplicates<T, TProp>(list, selector);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDuplicates instead.")]
        public static IEnumerable<string> GetDuplicates(this IEnumerable<string> list)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDuplicates(list);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDuplicates instead.")]
        public static IEnumerable<T> GetDuplicates<T>(this IEnumerable<T> list)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.GetDuplicates<T>(list);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEach instead.")]
        public static void ForEach<T>(this IEnumerable<T> list, Action<T> action)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEach<T>(list, action);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEach instead.")]
        public static void ForEach<T>(this IEnumerable<T> list, Action<T> action, int maxParallel = 5)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEach<T>(list, action, maxParallel);

#if (NET45_OR_GREATER || NET || NETSTANDARD2_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync instead.")]
        public static Task ForEachAsync<T>(this IEnumerable<T> list, Action<T> action, int maxParallel = 5)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync<T>(list, action, maxParallel);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync instead.")]
        public static Task<IEnumerable<TOutput>> ForEachAsync<TInput, TOutput>(
            this IEnumerable<TInput> list, Func<TInput, TOutput> function, int maxParallel = 5)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync<TInput, TOutput>(list, function, maxParallel);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync instead.")]
        public static Task<IEnumerable<TOutput>> ForEachAsync<TInput, TOutput>(
            this IEnumerable<TInput> list, Func<TInput, Task<TOutput>> function, int maxParallel = 5)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync<TInput, TOutput>(list, function, maxParallel);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync instead.")]
        public static Task ForEachAsync<TInput>(this IEnumerable<TInput> list, Func<TInput, Task> function, int maxParallel = 5)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAsync<TInput>(list, function, maxParallel);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAndReturn instead.")]
        public static IEnumerable<T> ForEachAndReturn<T>(this IEnumerable<T> list, Action<T> action)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ForEachAndReturn<T>(list, action);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Chunked instead.")]
        public static IEnumerable<IEnumerable<T>> Chunked<T>(this IEnumerable<T> source, int chunkSize = 100)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Chunked<T>(source, chunkSize);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AddIfNotExist instead.")]
        public static IEnumerable<T> AddIfNotExist<T>(this IEnumerable<T> source, T item)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.AddIfNotExist<T>(source, item);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Convert instead.")]
        public static TDest[] Convert<TSource, TDest>(this IEnumerable<TSource> source, Func<TSource, TDest> converter)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.Convert<TSource, TDest>(source, converter);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ConvertToQuerystring instead.")]
        public static string ConvertToQuerystring(this IEnumerable collection, string label)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ConvertToQuerystring(collection, label);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToHashSet instead.")]
        public static ISet<T> ToHashSet<T>(this IEnumerable<T> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.ToHashSet<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.HasAny instead.")]
        public static bool HasAny<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.HasAny<TSource>(source, predicate);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast instead.")]
        public static bool IsLast<T>(this IEnumerator<T> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast instead.")]
        public static bool IsLast<TKey, TValue>(
            this IEnumerator<KeyValuePair<TKey, TValue>> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.IsLast<TKey, TValue>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.EnumerableExtensions.SelectWithIsLast instead.")]
        public static IEnumerable<TupleResult<T, bool>> SelectWithIsLast<T>(
            this IEnumerable<T> source)
            => global::RzR.Extensions.Domain.Collections.EnumerableExtensions.SelectWithIsLast<T>(source);

    }
}
