// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.Helpers
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.IO.DirectoryHelper"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.IO.DirectoryHelper' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class DirectoryHelper
    {
        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.CreateDirectory instead.")]
        public static void CreateDirectory(string path)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.CreateDirectory(path);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.CopyDirectory instead.")]
        public static void CopyDirectory(DirectoryInfo source, DirectoryInfo target)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.CopyDirectory(source, target);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.CopyDirectory instead.")]
        public static void CopyDirectory(string sourcePath, string targetPath)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.CopyDirectory(sourcePath, targetPath);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.DeleteDirectory instead.")]
        public static void DeleteDirectory(DirectoryInfo source)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.DeleteDirectory(source);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.DeleteDirectory instead.")]
        public static void DeleteDirectory(string sourcePath)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.DeleteDirectory(sourcePath);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount instead.")]
        public static int FileCount(string directory)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount(directory);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount instead.")]
        public static int FileCount(string directory, SearchOption searchOption)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount(directory, searchOption);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount instead.")]
        public static int FileCount(string directory, SearchOption searchOption, string searchPattern)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.FileCount(directory, searchOption, searchPattern);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.DirectoryFileCount instead.")]
        public static Tuple<int, int> DirectoryFileCount(string directory)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.DirectoryFileCount(directory);

        [Obsolete("Use global::RzR.Extensions.Domain.IO.DirectoryHelper.ExistFileInDirectory instead.")]
        public static bool ExistFileInDirectory(string directoryWithFile)
            => global::RzR.Extensions.Domain.IO.DirectoryHelper.ExistFileInDirectory(directoryWithFile);

    }
}
