// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.CommonExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.NumbersExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.NumbersExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class NumbersExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.AreEqual instead.")]
        public static bool AreEqual(this float source, float toCompare, float epsilon = float.Epsilon)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.AreEqual(source, toCompare, epsilon);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.AreEqual instead.")]
        public static bool AreEqual(this double source, double toCompare, double epsilon = double.Epsilon)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.AreEqual(source, toCompare, epsilon);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetPercentage instead.")]
        public static double GetPercentage(this double value, int percentage)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetPercentage(value, percentage);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetPercentage instead.")]
        public static double GetPercentage(this decimal value, double percentage)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetPercentage(value, percentage);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf instead.")]
        public static int PercentOf(this int value, int total)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf(value, total);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf instead.")]
        public static int PercentOf(this ulong value, ulong total)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf(value, total);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf instead.")]
        public static double PercentOf(this decimal value, decimal total)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf(value, total);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf instead.")]
        public static int PercentOf(this long value, long total)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.PercentOf(value, total);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong instead.")]
        public static long NextLong(this Random random, long min, long max)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong(random, min, max);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong instead.")]
        public static long NextLong(this Random random, long max)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong(random, max);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong instead.")]
        public static long NextLong(this Random random)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.NextLong(random);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GenerateUniqueNumberThatNoIncludesNumbers instead.")]
        public static long GenerateUniqueNumberThatNoIncludesNumbers(this IEnumerable<long> excludeNumbers)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GenerateUniqueNumberThatNoIncludesNumbers(excludeNumbers);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsPrime instead.")]
        public static bool IsPrime(this int number)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsPrime(number);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.RoundTo instead.")]
        public static decimal RoundTo(this decimal value, int count)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.RoundTo(value, count);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.RoundTo instead.")]
        public static double RoundTo(this double value, int count)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.RoundTo(value, count);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsBetween instead.")]
        public static bool IsBetween(this double source, double lower, double higher)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsBetween(source, lower, higher);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsBetween instead.")]
        public static bool IsBetween(this int source, int lower, int higher)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.IsBetween(source, lower, higher);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetNumberSuffix instead.")]
        public static string GetNumberSuffix(this int sourceNumber)
            => global::RzR.Extensions.Domain.Primitives.NumbersExtensions.GetNumberSuffix(sourceNumber);

    }
}
