// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.ArraysExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Collections.DictionaryExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Collections.DictionaryExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class DictionaryExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddRange instead.")]
        public static Dictionary<TKey, TValue> AddRange<TKey, TValue>(this Dictionary<TKey, TValue> context,
            Dictionary<TKey, TValue> newItems)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddRange<TKey, TValue>(context, newItems);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.RemoveKeys instead.")]
        public static Dictionary<TKey, TValue> RemoveKeys<TKey, TValue>(this Dictionary<TKey, TValue> dict,
            IEnumerable<TKey> keys)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.RemoveKeys<TKey, TValue>(dict, keys);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.IndexOf instead.")]
        public static int IndexOf(this IDictionary dictionary, object value)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.IndexOf(dictionary, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.IsNullOrEmpty instead.")]
        public static bool IsNullOrEmpty(this IDictionary dictionary)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.IsNullOrEmpty(dictionary);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetStringOrDefault instead.")]
        public static string GetStringOrDefault(this Dictionary<string, string> dictionary, string key,
                    string @default = default)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetStringOrDefault(dictionary, key, default);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetGuidOrDefault instead.")]
        public static Guid GetGuidOrDefault(this Dictionary<string, string> dictionary, string key,
            Guid @default = default)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetGuidOrDefault(dictionary, key, default);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetIntOrDefault instead.")]
        public static int GetIntOrDefault(this Dictionary<string, string> dictionary, string key,
            int @default = default)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetIntOrDefault(dictionary, key, default);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetBoolOrDefault instead.")]
        public static bool GetBoolOrDefault(this Dictionary<string, string> dictionary, string key,
            bool @default = default)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetBoolOrDefault(dictionary, key, default);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddIfNotExist instead.")]
        public static void AddIfNotExist<TKey, TValue>(this IDictionary<TKey, TValue> source, KeyValuePair<TKey, TValue> item)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddIfNotExist<TKey, TValue>(source, item);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddIfNotExist instead.")]
        public static void AddIfNotExist<TKey, TValue>(this IDictionary<TKey, TValue> source, TKey key, TValue value)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddIfNotExist<TKey, TValue>(source, key, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.TryGetValue instead.")]
        public static TValue TryGetValue<TKey, TValue>(this IDictionary<TKey, TValue> source, TKey key)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.TryGetValue<TKey, TValue>(source, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetValueOrDefault instead.")]
        public static TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> source, TKey key)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.GetValueOrDefault<TKey, TValue>(source, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.ContainsAllKeys instead.")]
        public static bool ContainsAllKeys<TKey, TValue>(this IDictionary<TKey, TValue> source, params TKey[] keys)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.ContainsAllKeys<TKey, TValue>(source, keys);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.ContainsAnyKeys instead.")]
        public static bool ContainsAnyKeys<TKey, TValue>(this IDictionary<TKey, TValue> source, params TKey[] keys)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.ContainsAnyKeys<TKey, TValue>(source, keys);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdate instead.")]
        public static void AddOrUpdate<TKey, TValue>(this IDictionary<TKey, TValue> source, TKey key, TValue value)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdate<TKey, TValue>(source, key, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValue instead.")]
        public static void AddOrUpdateValue<TKey, TValue>(this IDictionary<TKey, TValue[]> source, TKey key, TValue value)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValue<TKey, TValue>(source, key, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValues instead.")]
        public static void AddOrUpdateValues<TKey, TValue>(this IDictionary<TKey, TValue[]> source, TKey key, TValue value)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValues<TKey, TValue>(source, key, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValues instead.")]
        public static void AddOrUpdateValues<TKey, TValue>(this IDictionary<TKey, TValue[]> source, TKey key, params TValue[] values)
            => global::RzR.Extensions.Domain.Collections.DictionaryExtensions.AddOrUpdateValues<TKey, TValue>(source, key, values);

    }
}
