// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.CommonExtensions.Reflection
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Reflection.TypeExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Reflection.TypeExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class TypeExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyValue instead.")]
        public static object GetPropertyValue(this object obj, string name)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyValue(obj, name);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyValue instead.")]
        public static string GetStringPropertyValue(this object obj, string name)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyValue(obj, name);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAnonymousType instead.")]
        public static bool IsAnonymousType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAnonymousType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNullablePropType instead.")]
        public static bool IsNullablePropType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNullablePropType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetValue instead.")]
        public static T GetValue<T>(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetValue<T>(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetSelectedFieldFromEntity instead.")]
        public static string GetSelectedFieldFromEntity(this Type type, IEnumerable<string> fields = null)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetSelectedFieldFromEntity(type, fields);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsSimpleType instead.")]
        public static bool IsSimpleType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsSimpleType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfInt instead.")]
        public static bool IsTypeOfInt(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfInt(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfNullableInt instead.")]
        public static bool IsTypeOfNullableInt(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfNullableInt(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfFloatingPoint instead.")]
        public static bool IsTypeOfFloatingPoint(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfFloatingPoint(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfNullableFloatingPoint instead.")]
        public static bool IsTypeOfNullableFloatingPoint(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsTypeOfNullableFloatingPoint(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsEnumType instead.")]
        public static bool IsEnumType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsEnumType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsStringType instead.")]
        public static bool IsStringType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsStringType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetNonNullableType instead.")]
        public static Type GetNonNullableType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetNonNullableType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyPath instead.")]
        public static PropertyInfo[] GetPropertyPath(this Type type, string propertyPath)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyPath(type, propertyPath);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAsType instead.")]
        public static bool IsAsType<T>(this Type target)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAsType<T>(target);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyInfos instead.")]
        public static IEnumerable<PropertyInfo> GetPropertyInfos(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetPropertyInfos(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyInfos instead.")]
        public static IEnumerable<PropertyInfo> GetStringPropertyInfos(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyInfos(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyNames instead.")]
        public static List<string> GetStringPropertyNames(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetStringPropertyNames(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNonAbstractClass instead.")]
        public static bool IsNonAbstractClass(this Type type, bool publicOnly, bool includeCompilerGenerated)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNonAbstractClass(type, publicOnly, includeCompilerGenerated);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetBaseTypes instead.")]
        public static IEnumerable<Type> GetBaseTypes(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetBaseTypes(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInNamespaceAlternative instead.")]
        public static bool IsInNamespaceAlternative(this Type type, string namespaceName)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInNamespaceAlternative(type, namespaceName);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInExactNamespace instead.")]
        public static bool IsInExactNamespace(this Type type, string namespaceName)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInExactNamespace(type, namespaceName);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute instead.")]
        public static bool HasAttribute(this Type type, Type attributeType)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute(type, attributeType);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute instead.")]
        public static bool HasAttribute<T>(this Type type) where T : Attribute
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute<T>(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute instead.")]
        public static bool HasAttribute<T>(this Type type, Func<T, bool> predicate) where T : Attribute
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.HasAttribute<T>(type, predicate);

#if (NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAssignableFromPortable instead.")]
        public static bool IsAssignableFromPortable(this Type baseType, Type derivedType)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAssignableFromPortable(baseType, derivedType);

#endif
#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericArguments instead.")]
        public static Type[] GetGenericArguments(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericArguments(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetMethod instead.")]
        public static MethodInfo GetMethod(this Type type, string name)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetMethod(type, name);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetMembers instead.")]
        public static IEnumerable<MemberInfo> GetMembers(this Type type, string name)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetMembers(type, name);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetInterfaces instead.")]
        public static IEnumerable<Type> GetInterfaces(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetInterfaces(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericType instead.")]
        public static bool IsGenericType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsValueType instead.")]
        public static bool IsValueType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsValueType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAbstract instead.")]
        public static bool IsAbstract(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAbstract(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAssignableFrom instead.")]
        public static bool IsAssignableFrom(this Type type, Type other)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsAssignableFrom(type, other);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.ContainsGenericParameters instead.")]
        public static bool ContainsGenericParameters(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.ContainsGenericParameters(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.BaseType instead.")]
        public static Type BaseType(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.BaseType(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericTypeDefinition instead.")]
        public static bool IsGenericTypeDefinition(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericTypeDefinition(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsPrimitive instead.")]
        public static bool IsPrimitive(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsPrimitive(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNestedPublic instead.")]
        public static bool IsNestedPublic(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsNestedPublic(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsPublic instead.")]
        public static bool IsPublic(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsPublic(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsSealed instead.")]
        public static bool IsSealed(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsSealed(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericParameterConstraints instead.")]
        public static Type[] GetGenericParameterConstraints(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericParameterConstraints(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsClass instead.")]
        public static bool IsClass(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsClass(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInterface instead.")]
        public static bool IsInterface(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInterface(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericParameter instead.")]
        public static bool IsGenericParameter(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsGenericParameter(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericParameterAttributes instead.")]
        public static GenericParameterAttributes GetGenericParameterAttributes(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetGenericParameterAttributes(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetAssembly instead.")]
        public static Assembly GetAssembly(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetAssembly(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructors instead.")]
        public static IEnumerable<ConstructorInfo> GetConstructors(this Type type, bool includeNonPublic)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructors(type, includeNonPublic);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructors instead.")]
        public static IEnumerable<ConstructorInfo> GetConstructors(this Type type)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructors(type);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructor instead.")]
        public static ConstructorInfo GetConstructor(this Type type, Type[] types)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.GetConstructor(type, types);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInNamespace instead.")]
        public static bool IsInNamespace(this Type type, string nameSpace)
            => global::RzR.Extensions.Domain.Reflection.TypeExtensions.IsInNamespace(type, nameSpace);

#endif
    }
}
