// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace DomainCommonExtensions.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.CharExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.CharExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class CharExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsMissing instead.")]
        public static bool IsMissing(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsMissing(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsPresent instead.")]
        public static bool IsPresent(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsPresent(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsDigit instead.")]
        public static bool IsDigit(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsDigit(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAscii instead.")]
        public static bool IsAscii(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAscii(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiLetter instead.")]
        public static bool IsAsciiLetter(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiLetter(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiUpper instead.")]
        public static bool IsAsciiUpper(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiUpper(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiLower instead.")]
        public static bool IsAsciiLower(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsAsciiLower(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsNewLine instead.")]
        public static bool IsNewLine(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsNewLine(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsQuote instead.")]
        public static bool IsQuote(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsQuote(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsBracket instead.")]
        public static bool IsBracket(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsBracket(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsOperator instead.")]
        public static bool IsOperator(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsOperator(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsMathSign instead.")]
        public static bool IsMathSign(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsMathSign(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsWhiteSpaceFast instead.")]
        public static bool IsWhiteSpaceFast(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsWhiteSpaceFast(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsSymbolOrPunctuation instead.")]
        public static bool IsSymbolOrPunctuation(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsSymbolOrPunctuation(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsBinaryDigit instead.")]
        public static bool IsBinaryDigit(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsBinaryDigit(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsOctalDigit instead.")]
        public static bool IsOctalDigit(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsOctalDigit(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsHexDigit instead.")]
        public static bool IsHexDigit(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsHexDigit(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.ToHexValue instead.")]
        public static int ToHexValue(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.ToHexValue(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.ToggleCase instead.")]
        public static char ToggleCase(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.ToggleCase(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsPrintable instead.")]
        public static bool IsPrintable(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsPrintable(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.Next instead.")]
        public static char Next(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.Next(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.Previous instead.")]
        public static char Previous(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.Previous(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsEmoji instead.")]
        public static bool IsEmoji(this char source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsEmoji(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.HasValue instead.")]
        public static bool HasValue(this char? source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.HasValue(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.DefaultIfNull instead.")]
        public static char DefaultIfNull(this char? source, char defaultChar)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.DefaultIfNull(source, defaultChar);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.IsNullOrWhiteSpace instead.")]
        public static bool IsNullOrWhiteSpace(this char? source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.IsNullOrWhiteSpace(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.CharExtensions.SpaceIfNull instead.")]
        public static char SpaceIfNull(this char? source)
            => global::RzR.Extensions.Domain.Primitives.CharExtensions.SpaceIfNull(source);

    }
}
