// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.CommonExtensions.TypeParam
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Reflection.TypeParam.TExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class TExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull instead.")]
        public static void IfNotNull<TInput>(this TInput source, Action<TInput> action)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull<TInput>(source, action);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull instead.")]
        public static void IfNull<TInput>(this TInput source, Action<TInput> action)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull<TInput>(source, action);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyValue instead.")]
        public static IEnumerable<TPropResultType> GetPropertyValue<TPropResultType, TSourceEntity>(this TSourceEntity source,
            params string[] fieldNames) where TPropResultType : struct where TSourceEntity : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyValue<TPropResultType, TSourceEntity>(source, fieldNames);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyStringValue instead.")]
        public static IEnumerable<string> GetPropertyStringValue<TSourceEntity>(this TSourceEntity source,
            params string[] fieldNames) where TSourceEntity : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyStringValue<TSourceEntity>(source, fieldNames);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyValue instead.")]
        public static IEnumerable<object> GetPropertyValue<TSourceEntity>(this TSourceEntity source,
            params string[] fieldNames) where TSourceEntity : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertyValue<TSourceEntity>(source, fieldNames);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.ChangePropertyValue instead.")]
        public static TEntityResult ChangePropertyValue<TEntityResult, TEntitySource>(
            this TEntityResult sourceResultEntry,
            TEntitySource sourceDataEntry, params string[] propsName) where TEntitySource : class where TEntityResult : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.ChangePropertyValue<TEntityResult, TEntitySource>(sourceResultEntry, sourceDataEntry, propsName);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.Clone instead.")]
        public static T Clone<T>(this T source)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.Clone<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.SerializeToXmlDoc instead.")]
        public static XmlDocument SerializeToXmlDoc<T>(this T source, string rootName = null, string rootNameSpaceName = null)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.SerializeToXmlDoc<T>(source, rootName, rootNameSpaceName);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.AppendTo instead.")]
        public static T[] AppendTo<T>(this T first, params T[] items)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.AppendTo<T>(first, items);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertiesInfoFromSource instead.")]
        public static IList<PropertyInfo> GetPropertiesInfoFromSource<TSource>(this TSource source) where TSource : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.GetPropertiesInfoFromSource<TSource>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNull instead.")]
        public static TSource IfIsNull<TSource>(this TSource source, TSource defaultValue)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNull<TSource>(source, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNotNull instead.")]
        public static TSource IfIsNotNull<TSource>(this TSource source, TSource defaultValue)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNotNull<TSource>(source, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.SubArray instead.")]
        public static T[] SubArray<T>(this T[] array, int offset, int length)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.SubArray<T>(array, offset, length);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfEquals instead.")]
        public static T IfEquals<T>(this T source, T searchValue, T resultValue)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfEquals<T>(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotEquals instead.")]
        public static T IfNotEquals<T>(this T source, T searchValue, T resultValue)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotEquals<T>(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.NotAllowNull instead.")]
        public static T NotAllowNull<T>(this T source, string parameterName) where T : class
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.NotAllowNull<T>(source, parameterName);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull instead.")]
        public static TResult IfNotNull<TInput, TResult>(this TInput source, Func<TInput, TResult> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull<TInput, TResult>(source, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull instead.")]
        public static TResult IfNotNull<TInput, TResult>(this TInput source, Func<TInput, TResult> func,
            TResult defaultValue)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull<TInput, TResult>(source, func, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull instead.")]
        public static TSource IfNull<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull instead.")]
        public static TSource IfNotNull<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull instead.")]
        public static TSource IfNotNull<TSource>(this TSource source, TSource defaultValue, Func<bool> func, bool isOrOperator)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNotNull<TSource>(source, defaultValue, func, isOrOperator);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull instead.")]
        public static TSource IfNull<TSource>(this TSource source, TSource defaultValue, Func<bool> func, bool isOrOperator, bool funcResult)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfNull<TSource>(source, defaultValue, func, isOrOperator, funcResult);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNullOrFuncIsTrue instead.")]
        public static TSource IfIsNullOrFuncIsTrue<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNullOrFuncIsTrue<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNullAndFuncIsTrue instead.")]
        public static TSource IfIsNullAndFuncIsTrue<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfIsNullAndFuncIsTrue<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFuncIsTrue instead.")]
        public static TSource IfFuncIsTrue<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFuncIsTrue<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFuncIsFalse instead.")]
        public static TSource IfFuncIsFalse<TSource>(this TSource source, TSource defaultValue, Func<bool> func)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFuncIsFalse<TSource>(source, defaultValue, func);

        [Obsolete("Use global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFunc instead.")]
        public static TSource IfFunc<TSource>(this TSource source, TSource defaultValue, Func<bool> func,
            bool funcResult)
            => global::RzR.Extensions.Domain.Reflection.TypeParam.TExtensions.IfFunc<TSource>(source, defaultValue, func, funcResult);

    }
}
