// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.ArraysExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class ConcurrentQueueExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Purge instead.")]
        public static void Purge<T>(this ConcurrentQueue<T> queue)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Purge<T>(queue);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Prune instead.")]
        public static void Prune<T>(this ConcurrentQueue<T> queue, int maxSize)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Prune<T>(queue, maxSize);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueAll instead.")]
        public static T[] DequeueAll<T>(this ConcurrentQueue<T> queue)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueAll<T>(queue);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueBatch instead.")]
        public static T[] DequeueBatch<T>(this ConcurrentQueue<T> queue, int batchSize)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueBatch<T>(queue, batchSize);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.EnqueueRange instead.")]
        public static void EnqueueRange<T>(this ConcurrentQueue<T> queue, IEnumerable<T> items)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.EnqueueRange<T>(queue, items);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Enqueue instead.")]
        public static int Enqueue<T>(this ConcurrentQueue<T> queue, T item, int limit)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.Enqueue<T>(queue, item, limit);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.EnqueueRange instead.")]
        public static int EnqueueRange<T>(this ConcurrentQueue<T> queue, IEnumerable<T> items, int limit)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.EnqueueRange<T>(queue, items, limit);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueAndProcessBatches instead.")]
        public static void DequeueAndProcessBatches<T>(this ConcurrentQueue<T> queue, int maxBatchSize,
            Action<T[]> processBatch)
            => global::RzR.Extensions.Domain.Collections.ConcurrentQueueExtensions.DequeueAndProcessBatches<T>(queue, maxBatchSize, processBatch);

    }
}
