// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.CommonExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Cryptography.CryptoExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Cryptography.CryptoExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class CryptoExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.CryptoExtensions.AesEncryptString instead.")]
        public static string AesEncryptString(this string plainText, string key, byte[] iv, bool isLongStringKey = false, int keySize = 256, int blockSize = 128)
            => global::RzR.Extensions.Domain.Cryptography.CryptoExtensions.AesEncryptString(plainText, key, iv, isLongStringKey, keySize, blockSize);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.CryptoExtensions.AesDecryptString instead.")]
        public static string AesDecryptString(this string cipherText, string key, byte[] iv, bool isLongStringKey = false, int keySize = 256, int blockSize = 128)
            => global::RzR.Extensions.Domain.Cryptography.CryptoExtensions.AesDecryptString(cipherText, key, iv, isLongStringKey, keySize, blockSize);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptWithRSA instead.")]
        public static string EncryptWithRSA(this string stringToEncrypt, string key)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptWithRSA(stringToEncrypt, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptWithRSA instead.")]
        public static string DecryptWithRSA(this string stringToDecrypt, string key)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptWithRSA(stringToDecrypt, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSAXmlKey instead.")]
        public static string EncryptRSAXmlKey(this string stringToEncrypt, int keySize, string publicKey, bool isKeyBase64Encoded = false)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSAXmlKey(stringToEncrypt, keySize, publicKey, isKeyBase64Encoded);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSAXmlKey instead.")]
        public static string DecryptRSAXmlKey(this string stringToDecrypt, int keySize, string privateKey, bool isKeyBase64Encoded = false)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSAXmlKey(stringToDecrypt, keySize, privateKey, isKeyBase64Encoded);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSACertificate instead.")]
        public static string EncryptRSACertificate(this string stringToEncrypt, RSACryptoServiceProvider publicKey)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSACertificate(stringToEncrypt, publicKey);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSACertificate instead.")]
        public static string DecryptRSACertificate(this string stringToDecrypt, RSACryptoServiceProvider privateKey)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSACertificate(stringToDecrypt, privateKey);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSACertificate instead.")]
        public static string EncryptRSACertificate(this string stringToEncrypt, X509Certificate2 certificate)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.EncryptRSACertificate(stringToEncrypt, certificate);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSACertificate instead.")]
        public static string DecryptRSACertificate(this string stringToDecrypt, X509Certificate2 certificate)
            => global::RzR.Extensions.Domain.Cryptography.Rsa.CryptoExtensions.DecryptRSACertificate(stringToDecrypt, certificate);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.CryptoExtensions.TEAEncrypt instead.")]
        public static string TEAEncrypt(this string stringToEncrypt, string key, out string passCode)
            => global::RzR.Extensions.Domain.Cryptography.Tea.CryptoExtensions.TEAEncrypt(stringToEncrypt, key, out passCode);

        [Obsolete("Use global::RzR.Extensions.Domain.Cryptography.Tea.CryptoExtensions.TEADecrypt instead.")]
        public static string TEADecrypt(this string stringToDecrypt, string key)
            => global::RzR.Extensions.Domain.Cryptography.Tea.CryptoExtensions.TEADecrypt(stringToDecrypt, key);

    }
}
