// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Text.StringExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Text.StringExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class StringExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Split instead.")]
        public static string[] Split(this string str, string delimiter)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Split(str, delimiter);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FirstCharToUpper instead.")]
        public static string FirstCharToUpper(this string input)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FirstCharToUpper(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FirstCharToLower instead.")]
        public static string FirstCharToLower(this string input)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FirstCharToLower(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsNullOrEmpty instead.")]
        public static bool IsNullOrEmpty(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsNullOrEmpty(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidEmail instead.")]
        public static bool IsValidEmail(this string email)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidEmail(email);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToSecureString instead.")]
        public static SecureString ToSecureString(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToSecureString(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.StripHtml instead.")]
        public static string StripHtml(this string input)
            => global::RzR.Extensions.Domain.Text.StringExtensions.StripHtml(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Truncate instead.")]
        public static string Truncate(this string text, int maxLength, bool useDots = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Truncate(text, maxLength, useDots);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TruncateFromStart instead.")]
        public static string TruncateFromStart(this string text, int maxLength, bool useDots = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TruncateFromStart(text, maxLength, useDots);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TruncateExactLength instead.")]
        public static string TruncateExactLength(this string value, int maxLength)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TruncateExactLength(value, maxLength);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidUrl instead.")]
        public static bool IsValidUrl(this string text)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidUrl(text);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidIpAddress instead.")]
        public static bool IsValidIpAddress(this string s)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidIpAddress(s);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToBytes instead.")]
        public static byte[] ToBytes(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToBytes(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Utf8ToBytes instead.")]
        public static byte[] Utf8ToBytes(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Utf8ToBytes(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.DecodeFromUtf8 instead.")]
        public static string DecodeFromUtf8(this string utf8String)
            => global::RzR.Extensions.Domain.Text.StringExtensions.DecodeFromUtf8(utf8String);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToHexString instead.")]
        public static string ToHexString(this string clearText, bool withSpace = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToHexString(clearText, withSpace);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToStringHex instead.")]
        public static string ToStringHex(this string hexString, bool withSpace = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToStringHex(hexString, withSpace);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToByteHex instead.")]
        public static byte[] ToByteHex(this string hexString, bool withSpace = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToByteHex(hexString, withSpace);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimIfNotNull instead.")]
        public static string TrimIfNotNull(this string value)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimIfNotNull(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimAndReduceSpace instead.")]
        public static string TrimAndReduceSpace(this string value, bool reduceAllSpaces = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimAndReduceSpace(value, reduceAllSpaces);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidEmailWithMailAddress instead.")]
        public static bool IsValidEmailWithMailAddress(this string emailAddress)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidEmailWithMailAddress(emailAddress);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetFileNameAndExtenstion instead.")]
        public static string[] GetFileNameAndExtenstion(this string fullName)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetFileNameAndExtenstion(fullName);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Base64Encode instead.")]
        public static string Base64Encode(this string plainText)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Base64Encode(plainText);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Base64Decode instead.")]
        public static string Base64Decode(this string base64EncodedData)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Base64Decode(base64EncodedData);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FrontAppendMoveUpInDirectory instead.")]
        public static string FrontAppendMoveUpInDirectory(this string currentPath, int noOfLevels)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FrontAppendMoveUpInDirectory(currentPath, noOfLevels);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.MoveUpInDirectoryBackAppend instead.")]
        public static string MoveUpInDirectoryBackAppend(this string currentPath, int noOfLevels)
            => global::RzR.Extensions.Domain.Text.StringExtensions.MoveUpInDirectoryBackAppend(currentPath, noOfLevels);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FormatToDate instead.")]
        public static DateTime? FormatToDate(this string inputStringDate)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FormatToDate(inputStringDate);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.RemoveSpecialChars instead.")]
        public static string RemoveSpecialChars(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.RemoveSpecialChars(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimAndReplaceSpecialCharacters instead.")]
        public static string TrimAndReplaceSpecialCharacters(this string value, bool reduceAllSpaces = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimAndReplaceSpecialCharacters(value, reduceAllSpaces);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimEndCharAndReduceLastWhiteSpace instead.")]
        public static string TrimEndCharAndReduceLastWhiteSpace(this string value, char reduce)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimEndCharAndReduceLastWhiteSpace(value, reduce);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimEndCharAndReduceLastWhiteSpace instead.")]
        public static string TrimEndCharAndReduceLastWhiteSpace(this string value, char[] reduce)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimEndCharAndReduceLastWhiteSpace(value, reduce);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha1CryptoProv instead.")]
        public static byte[] GetHashSha1CryptoProv(this string content)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha1CryptoProv(content);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256CryptoProv instead.")]
        public static byte[] GetHashSha256CryptoProv(this string content)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256CryptoProv(content);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256 instead.")]
        public static byte[] GetHashSha256(this string inputString)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256(inputString);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256String instead.")]
        public static string GetHashSha256String(this string inputString)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha256String(inputString);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Sha256Hex instead.")]
        public static string Sha256Hex(this string inputString)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Sha256Hex(inputString);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.DeCodeBytesFromBase64 instead.")]
        public static byte[] DeCodeBytesFromBase64(this string encoded)
            => global::RzR.Extensions.Domain.Text.StringExtensions.DeCodeBytesFromBase64(encoded);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToBase64Url instead.")]
        public static string ToBase64Url(this string input)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToBase64Url(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FromBase64Url instead.")]
        public static string FromBase64Url(this string base64Url)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FromBase64Url(base64Url);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToSlug instead.")]
        public static string ToSlug(this string input, CultureInfo culture = null, int maxLength = 0)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToSlug(input, culture, maxLength);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Mask instead.")]
        public static string Mask(this string input, string pattern, char maskChar = '*')
            => global::RzR.Extensions.Domain.Text.StringExtensions.Mask(input, pattern, maskChar);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsBase64String instead.")]
        public static bool IsBase64String(this string base64String)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsBase64String(base64String);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ReplaceSpecialCharacters instead.")]
        public static string ReplaceSpecialCharacters(this string data)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ReplaceSpecialCharacters(data);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Next instead.")]
        public static string Next(this string value)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Next(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Next instead.")]
        public static string Next(this string value, uint next)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Next(value, next);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FromUnicode instead.")]
        public static string FromUnicode(this string unicodeString)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FromUnicode(unicodeString);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TryParseGuidNullable instead.")]
        public static Guid? TryParseGuidNullable(this string val)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TryParseGuidNullable(val);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.UppercaseWords instead.")]
        public static string UppercaseWords(this string value)
            => global::RzR.Extensions.Domain.Text.StringExtensions.UppercaseWords(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetBytes instead.")]
        public static byte[] GetBytes(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetBytes(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FilterXml instead.")]
        public static string FilterXml(this string xml)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FilterXml(xml);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.SimpleCompareTwoString instead.")]
        public static double SimpleCompareTwoString(this string a, string b)
            => global::RzR.Extensions.Domain.Text.StringExtensions.SimpleCompareTwoString(a, b);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GenerateStringPermutation instead.")]
        public static List<string> GenerateStringPermutation(this string inputData)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GenerateStringPermutation(inputData);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GenerateStringOrderedList instead.")]
        public static List<string> GenerateStringOrderedList(this string inputData)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GenerateStringOrderedList(inputData);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ValidatePull instead.")]
        public static bool ValidatePull(this string source, IEnumerable<string> pull)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ValidatePull(source, pull);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FixBase64ForImage instead.")]
        public static string FixBase64ForImage(this string image)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FixBase64ForImage(image);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToEnum instead.")]
        public static T ToEnum<T>(this string value)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToEnum<T>(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToBytesUnicode instead.")]
        public static byte[] ToBytesUnicode(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToBytesUnicode(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ReplaceExact instead.")]
        public static string ReplaceExact(this string input, string oldValue, string newValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ReplaceExact(input, oldValue, newValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfNullOrWhiteSpace instead.")]
        public static string IfNullOrWhiteSpace(this string input, string defaultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfNullOrWhiteSpace(input, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfNullOrEmpty instead.")]
        public static string IfNullOrEmpty(this string input, string defaultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfNullOrEmpty(input, defaultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToLines instead.")]
        public static string[] ToLines(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToLines(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Chunked instead.")]
        public static IEnumerable<string> Chunked(this string source, int size, bool isRightAlign = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Chunked(source, size, isRightAlign);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsEmpty instead.")]
        public static bool IsEmpty(this string str)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsEmpty(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.XmlEncode instead.")]
        public static string XmlEncode(this string xml)
            => global::RzR.Extensions.Domain.Text.StringExtensions.XmlEncode(xml);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.XmlDecode instead.")]
        public static string XmlDecode(this string xml)
            => global::RzR.Extensions.Domain.Text.StringExtensions.XmlDecode(xml);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.DeserializeToObject instead.")]
        public static object DeserializeToObject(this string xml, Type toType)
            => global::RzR.Extensions.Domain.Text.StringExtensions.DeserializeToObject(xml, toType);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Contains instead.")]
        public static bool Contains(this string source, string check, StringComparison comp)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Contains(source, check, comp);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ParseToInt instead.")]
        public static int ParseToInt(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ParseToInt(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ParseNullableInt instead.")]
        public static int? ParseNullableInt(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ParseNullableInt(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TryParseInt instead.")]
        public static bool TryParseInt(this string source, out int result)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TryParseInt(source, out result);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha512String instead.")]
        public static string GetHashSha512String(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetHashSha512String(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FromSpaceSeparatedString instead.")]
        public static IEnumerable<string> FromSpaceSeparatedString(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FromSpaceSeparatedString(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsMissing instead.")]
        public static bool IsMissing(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsMissing(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsPresent instead.")]
        public static bool IsPresent(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsPresent(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AddQueryString instead.")]
        public static string AddQueryString(this string url, string query)
            => global::RzR.Extensions.Domain.Text.StringExtensions.AddQueryString(url, query);

#if (NET || NETSTANDARD2_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AddQueryString instead.")]
        public static string AddQueryString(this string url, string name, string value)
            => global::RzR.Extensions.Domain.Text.StringExtensions.AddQueryString(url, name, value);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AddHashFragment instead.")]
        public static string AddHashFragment(this string url, string query)
            => global::RzR.Extensions.Domain.Text.StringExtensions.AddHashFragment(url, query);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.GetOrigin instead.")]
        public static string GetOrigin(this string url)
            => global::RzR.Extensions.Domain.Text.StringExtensions.GetOrigin(url);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Obfuscate instead.")]
        public static string Obfuscate(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Obfuscate(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AsRedacted instead.")]
        public static string AsRedacted(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.AsRedacted(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimPrefix instead.")]
        public static string TrimPrefix(this string source, string prefix, StringComparison stringComparision = StringComparison.OrdinalIgnoreCase)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimPrefix(source, prefix, stringComparision);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.TrimSuffix instead.")]
        public static string TrimSuffix(this string source, string suffix, StringComparison stringComparision = StringComparison.OrdinalIgnoreCase)
            => global::RzR.Extensions.Domain.Text.StringExtensions.TrimSuffix(source, suffix, stringComparision);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfNullThenEmpty instead.")]
        public static string IfNullThenEmpty(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfNullThenEmpty(source);

#if (NET || NETSTANDARD2_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJson instead.")]
        public static bool IsValidJson(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJson(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJsonObject instead.")]
        public static bool IsValidJsonObject(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJsonObject(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJsonArray instead.")]
        public static bool IsValidJsonArray(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsValidJsonArray(source);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.EscapeBackSlash instead.")]
        public static string EscapeBackSlash(this string source, string customCharEscape = "|")
            => global::RzR.Extensions.Domain.Text.StringExtensions.EscapeBackSlash(source, customCharEscape);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToStringArray instead.")]
        public static string[] ToStringArray(this string source, bool returnEmptyIfMissing = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToStringArray(source, returnEmptyIfMissing);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ArrayToString instead.")]
        public static string ArrayToString(this string[] source, bool returnEmptyIfMissing = false)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ArrayToString(source, returnEmptyIfMissing);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsGuid instead.")]
        public static bool IsGuid(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsGuid(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.ToGuid instead.")]
        public static Guid ToGuid(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.ToGuid(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FromDoubleQuotesWithBackSlashesToGuid instead.")]
        public static Guid FromDoubleQuotesWithBackSlashesToGuid(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FromDoubleQuotesWithBackSlashesToGuid(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.FormatWith instead.")]
        public static string FormatWith(this string source, params object[] args)
            => global::RzR.Extensions.Domain.Text.StringExtensions.FormatWith(source, args);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfContains instead.")]
        public static string IfContains(this string source, string searchValue, string resultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfContains(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfNotContains instead.")]
        public static string IfNotContains(this string source, string searchValue, string resultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfNotContains(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfStartsWith instead.")]
        public static string IfStartsWith(this string source, string searchValue, string resultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfStartsWith(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfNotStartsWith instead.")]
        public static string IfNotStartsWith(this string source, string searchValue, string resultValue)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfNotStartsWith(source, searchValue, resultValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsBase32String instead.")]
        public static bool IsBase32String(this string base32String, bool paddingCheck = true)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsBase32String(base32String, paddingCheck);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Base32ToBytes instead.")]
        public static byte[] Base32ToBytes(this string base32String)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Base32ToBytes(base32String);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Base32Encode instead.")]
        public static string Base32Encode(this string sourceString, bool includePadding = true)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Base32Encode(sourceString, includePadding);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.Base32Decode instead.")]
        public static string Base32Decode(this string sourceString)
            => global::RzR.Extensions.Domain.Text.StringExtensions.Base32Decode(sourceString);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.NotAllowedEmpty instead.")]
        public static string NotAllowedEmpty(this string source, string parameterName)
            => global::RzR.Extensions.Domain.Text.StringExtensions.NotAllowedEmpty(source, parameterName);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AddPeriod instead.")]
        public static string AddPeriod(this string source, string periodDelimiter = ".")
            => global::RzR.Extensions.Domain.Text.StringExtensions.AddPeriod(source, periodDelimiter);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.RemovePeriod instead.")]
        public static string RemovePeriod(this string source, string periodDelimiter = ".")
            => global::RzR.Extensions.Domain.Text.StringExtensions.RemovePeriod(source, periodDelimiter);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.AddPeriodValue instead.")]
        public static string AddPeriodValue(this string source, string periodDelimiter = ".", string period = "")
            => global::RzR.Extensions.Domain.Text.StringExtensions.AddPeriodValue(source, periodDelimiter, period);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.RemovePeriodValue instead.")]
        public static string RemovePeriodValue(this string source, string periodDelimiter = ".", string period = "")
            => global::RzR.Extensions.Domain.Text.StringExtensions.RemovePeriodValue(source, periodDelimiter, period);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsAllUpperCase instead.")]
        public static bool IsAllUpperCase(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsAllUpperCase(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsAllLowerCase instead.")]
        public static bool IsAllLowerCase(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsAllLowerCase(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsAllLetters instead.")]
        public static bool IsAllLetters(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsAllLetters(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.CleanTextToLettersNumbersAndSpace instead.")]
        public static string CleanTextToLettersNumbersAndSpace(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.CleanTextToLettersNumbersAndSpace(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsWebUrl instead.")]
        public static bool IsWebUrl(this string source)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsWebUrl(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.RemoveStartChars instead.")]
        public static string RemoveStartChars(this string source, int length)
            => global::RzR.Extensions.Domain.Text.StringExtensions.RemoveStartChars(source, length);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.RemoveEndChars instead.")]
        public static string RemoveEndChars(this string source, int length)
            => global::RzR.Extensions.Domain.Text.StringExtensions.RemoveEndChars(source, length);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IsMissingOrAny instead.")]
        public static bool IsMissingOrAny(this string source, params string[] checkValues)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IsMissingOrAny(source, checkValues);

        [Obsolete("Use global::RzR.Extensions.Domain.Text.StringExtensions.IfIsMissingOrAny instead.")]
        public static void IfIsMissingOrAny(this string source, Action execAction, params string[] checkValues)
            => global::RzR.Extensions.Domain.Text.StringExtensions.IfIsMissingOrAny(source, execAction, checkValues);

    }
}
