// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.ArraysExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class ConcurrentDictionaryExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate instead.")]
        public static void AddOrUpdate<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> source, 
            TKey key, TValue value)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate<TKey, TValue>(source, key, value);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate instead.")]
        public static void AddOrUpdate<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> source,
            KeyValuePair<TKey, TValue> keyValuePair)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate<TKey, TValue>(source, keyValuePair);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate instead.")]
        public static void AddOrUpdate<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> source, 
            IEnumerable<KeyValuePair<TKey, TValue>> keyValuePairs)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.AddOrUpdate<TKey, TValue>(source, keyValuePairs);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.Remove instead.")]
        public static void Remove<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary, TKey key)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.Remove<TKey, TValue>(dictionary, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.Remove instead.")]
        public static void Remove<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary,
            IEnumerable<TKey> keys)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.Remove<TKey, TValue>(dictionary, keys);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveWhere instead.")]
        public static void RemoveWhere<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary,
            Func<TValue, bool> predicate)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveWhere<TKey, TValue>(dictionary, predicate);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.TryRemove instead.")]
        public static void TryRemove<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary, TKey key)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.TryRemove<TKey, TValue>(dictionary, key);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveAll instead.")]
        public static void RemoveAll<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary,
            IEnumerable<TKey> keys)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveAll<TKey, TValue>(dictionary, keys);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveAll instead.")]
        public static void RemoveAll<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary,
            Func<TValue, bool> predicate)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.RemoveAll<TKey, TValue>(dictionary, predicate);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.GetValueOrDefault instead.")]
        public static TValue GetValueOrDefault<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dictionary,
            TKey key)
            => global::RzR.Extensions.Domain.Collections.ConcurrentDictionaryExtensions.GetValueOrDefault<TKey, TValue>(dictionary, key);

    }
}
