// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.ObjectExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.ObjectExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class ObjectExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.TryGetDateTimeFromDbObj instead.")]
        public static DateTime? TryGetDateTimeFromDbObj(this object value)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.TryGetDateTimeFromDbObj(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.TryCast instead.")]
        public static bool TryCast<T>(this object obj, out T result)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.TryCast<T>(obj, out result);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.GetXmlParams instead.")]
        public static void GetXmlParams(this object obj, ref XmlDocument xmlDocument)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.GetXmlParams(obj, ref xmlDocument);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.CopyPropertiesTo instead.")]
        public static void CopyPropertiesTo(this object fromObject, object toObject)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.CopyPropertiesTo(fromObject, toObject);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.GetPropertyHash instead.")]
        public static Hashtable GetPropertyHash(this object properties)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.GetPropertyHash(properties);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.In instead.")]
        public static bool In(this object obj, IEnumerable collection)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.In(obj, collection);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.ToDictionary instead.")]
        public static IDictionary<string, object> ToDictionary(this object obj)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.ToDictionary(obj);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.ToSafeString instead.")]
        public static string ToSafeString(this object source)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.ToSafeString(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.To instead.")]
        public static T To<T>(this object source)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.To<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.ObjectExtensions.SerializeToString instead.")]
        public static string SerializeToString(this object obj)
            => global::RzR.Extensions.Domain.Primitives.ObjectExtensions.SerializeToString(obj);

    }
}
