// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.DateTimeExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.DateTimeExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class DateTimeExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsUtc instead.")]
        public static DateTime AsUtc(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsUtc(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsUtc instead.")]
        public static DateTime? AsUtc(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsUtc(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FormatDateToString_112 instead.")]
        public static string FormatDateToString_112(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FormatDateToString_112(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FormatToString instead.")]
        public static string FormatToString(this DateTime input, string format = null)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FormatToString(input, format);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.CheckCultureDateTime instead.")]
        public static bool CheckCultureDateTime(this string value, string cultureInfo)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.CheckCultureDateTime(value, cultureInfo);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.TimeBetween instead.")]
        public static bool TimeBetween(this DateTime input, int hourStart, int hourStop)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.TimeBetween(input, hourStart, hourStop);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.CalculateAge instead.")]
        public static int CalculateAge(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.CalculateAge(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsNotNull instead.")]
        public static DateTime AsNotNull(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsNotNull(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsNotNull instead.")]
        public static DateTime AsNotNull(this DateTime? input, DateTime defaultDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsNotNull(input, defaultDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMinDateTimeOnNull instead.")]
        public static DateTime AsMinDateTimeOnNull(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMinDateTimeOnNull(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMaxDateTimeOnNull instead.")]
        public static DateTime AsMaxDateTimeOnNull(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMaxDateTimeOnNull(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMinDateOnNull instead.")]
        public static DateTime AsMinDateOnNull(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMinDateOnNull(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMaxDateOnNull instead.")]
        public static DateTime AsMaxDateOnNull(this DateTime? input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.AsMaxDateOnNull(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfDay instead.")]
        public static DateTime EndOfDay(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfDay(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfDay instead.")]
        public static DateTime StartOfDay(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfDay(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DayIndex instead.")]
        public static int DayIndex(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DayIndex(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.Intersects instead.")]
        public static bool Intersects(this DateTime startDate, DateTime endDate, DateTime intersectingStartDate,
            DateTime intersectingEndDate)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.Intersects(startDate, endDate, intersectingStartDate, intersectingEndDate);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsWeekend instead.")]
        public static bool IsWeekend(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsWeekend(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsLeapYear instead.")]
        public static bool IsLeapYear(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsLeapYear(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToTimeStamp instead.")]
        public static double ToTimeStamp(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToTimeStamp(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfWeek instead.")]
        public static DateTime StartOfWeek(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfWeek(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfWeek instead.")]
        public static DateTime EndOfWeek(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfWeek(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfMonth instead.")]
        public static DateTime StartOfMonth(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfMonth(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfMonth instead.")]
        public static DateTime EndOfMonth(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfMonth(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfPreviousMonth instead.")]
        public static DateTime StartOfPreviousMonth(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfPreviousMonth(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfPreviousMonth instead.")]
        public static DateTime EndOfPreviousMonth(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfPreviousMonth(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfYear instead.")]
        public static DateTime StartOfYear(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.StartOfYear(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfYear instead.")]
        public static DateTime EndOfYear(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.EndOfYear(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DaysInMonth instead.")]
        public static int DaysInMonth(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DaysInMonth(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DaysInYear instead.")]
        public static int DaysInYear(this DateTime input)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.DaysInYear(input);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.GetIso8601WeekOfYear instead.")]
        public static int GetIso8601WeekOfYear(this DateTime time)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.GetIso8601WeekOfYear(time);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToEpochTime instead.")]
        public static long ToEpochTime(this DateTime sourceTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToEpochTime(sourceTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToEpoch instead.")]
        public static long ToEpoch(this DateTime sourceTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToEpoch(sourceTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FromEpoch instead.")]
        public static DateTime FromEpoch(long milliseconds)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.FromEpoch(milliseconds);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToExcelTime instead.")]
        public static double ToExcelTime(this DateTime sourceTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ToExcelTime(sourceTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.Epoch instead.")]
        public static DateTime Epoch(this DateTime sourceTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.Epoch(sourceTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsOnlyDate instead.")]
        public static bool IsOnlyDate(this DateTime sourceDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsOnlyDate(sourceDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsOnlyDate instead.")]
        public static bool IsOnlyDate(this DateTime? sourceDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsOnlyDate(sourceDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero instead.")]
        public static DateTime ForceMillisecondsToZero(this DateTime sourceDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero(sourceDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero instead.")]
        public static DateTime? ForceMillisecondsToZero(this DateTime? sourceDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero(sourceDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero instead.")]
        public static DateTime ForceMillisecondsToZero(this DateTime? sourceDateTime, DateTime defaultDateTime)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.ForceMillisecondsToZero(sourceDateTime, defaultDateTime);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsDifferentDay instead.")]
        public static bool IsDifferentDay(this DateTime date, DateTime otherDate)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsDifferentDay(date, otherDate);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsDifferentLocalDay instead.")]
        public static bool IsDifferentLocalDay(this DateTime date, DateTime otherDate)
            => global::RzR.Extensions.Domain.Primitives.DateTimeExtensions.IsDifferentLocalDay(date, otherDate);

    }
}
