// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.DataTypeExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Primitives.EnumExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Primitives.EnumExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class EnumExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumDefinition instead.")]
        public static Dictionary<int, string> GetEnumDefinition(this Type enumType)
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumDefinition(enumType);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumMemberValue instead.")]
        public static string GetEnumMemberValue<T>(this T value) where T : struct, Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumMemberValue<T>(value);

#endif
#if (NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToEnumMemberValue instead.")]
        public static T ToEnumMemberValue<T>(this string str) where T : struct, Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToEnumMemberValue<T>(str);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToInt instead.")]
        public static int ToInt<T>(this T source) where T : Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToInt<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToInt instead.")]
        public static int? ToInt<T>(this T? source) where T : struct, Enum, IComparable, IFormattable
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToInt<T>(source);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToString instead.")]
        public static string ToString<T>(this T source) where T : Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.ToString<T>(source);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDescription instead.")]
        public static string GetDescription(this Enum value, bool returnEmpty = false)
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDescription(value, returnEmpty);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumValue instead.")]
        public static T GetEnumValue<T>(this string str) where T : struct, Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumValue<T>(str);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumValue instead.")]
        public static T GetEnumValue<T>(this int intValue) where T : struct, Enum, IConvertible
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetEnumValue<T>(intValue);

#if (NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER)
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDisplayName instead.")]
        public static string GetDisplayName(this Enum value)
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDisplayName(value);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDisplayDescription instead.")]
        public static string GetDisplayDescription(this Enum value)
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.GetDisplayDescription(value);

#endif
        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.AreEquals instead.")]
        public static bool AreEquals<T>(this T sourceEnumValue, T compareEnumValue) where T : Enum, IComparable, IFormattable
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.AreEquals<T>(sourceEnumValue, compareEnumValue);

        [Obsolete("Use global::RzR.Extensions.Domain.Primitives.EnumExtensions.IsDefined instead.")]
        public static T IsDefined<T>(this T value, string parameterName) where T : struct, Enum
            => global::RzR.Extensions.Domain.Primitives.EnumExtensions.IsDefined<T>(value, parameterName);

    }
}
