// <auto-generated>
//   Backward-compatibility shim file generated by build/ShimGenerator.
//   Do NOT edit manually. Regenerate with:
//     dotnet run --project build/ShimGenerator -- "<repo>/src/DomainCommonExtensions"
//   Each member here forwards to the new (v5) location and is marked [Obsolete].
// </auto-generated>
#nullable disable
#pragma warning disable CS0618 // calling members of [Obsolete] forwarder targets is intentional
#pragma warning disable CS1591 // missing XML doc on a generated forwarder
#pragma warning disable IDE0130 // namespace does not match folder structure -- intentional for shims
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using RzR.Extensions.Domain.Async;
using RzR.Extensions.Domain.Collections;
using RzR.Extensions.Domain.Collections.Types;
using RzR.Extensions.Domain.Cryptography;
using RzR.Extensions.Domain.Cryptography.Passwords;
using RzR.Extensions.Domain.Cryptography.Rsa;
using RzR.Extensions.Domain.Cryptography.Tea;
using RzR.Extensions.Domain.Data;
using RzR.Extensions.Domain.Data.DataReader;
using RzR.Extensions.Domain.Diagnostics;
using RzR.Extensions.Domain.Internal;
using RzR.Extensions.Domain.IO;
using RzR.Extensions.Domain.IO.Ini;
using RzR.Extensions.Domain.Linq;
using RzR.Extensions.Domain.Models;
using RzR.Extensions.Domain.Primitives;
using RzR.Extensions.Domain.Reflection;
using RzR.Extensions.Domain.Reflection.TypeParam;
using RzR.Extensions.Domain.Text;
using RzR.Extensions.Domain.Validation;
#if NET45_OR_GREATER || NET || NETSTANDARD1_0_OR_GREATER
using RzR.Extensions.Domain.Async.LazyLoad;
#endif
using PropertyAttributes = System.Reflection.PropertyAttributes;

namespace RzR.Extensions.Domain.ArraysExtensions
{
    /// <summary>Backward-compatibility shim. All members forward to <see cref="global::RzR.Extensions.Domain.Collections.CollectionExtensions"/>.</summary>
    [Obsolete("Type moved to 'RzR.Extensions.Domain.Collections.CollectionExtensions' in v5. Update your usings; this shim will be removed in a future release.", error: false)]
    public static class CollectionExtensions
    {
        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.AddRange instead.")]
        public static ICollection<TTarget> AddRange<TTarget>(this ICollection<TTarget> context,
            IEnumerable<TTarget> data)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.AddRange<TTarget>(context, data);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.DistinctBy instead.")]
        public static IEnumerable<TSource> DistinctBy<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.DistinctBy<TSource, TKey>(source, keySelector);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.ToKeyValuePair instead.")]
        public static IEnumerable<KeyValuePair<string, string>> ToKeyValuePair(this NameValueCollection collection)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.ToKeyValuePair(collection);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.In instead.")]
        public static bool In<T>(this T val, params T[] values) where T : struct
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.In<T>(val, values);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.With instead.")]
        public static ICollection<T> With<T>(this ICollection<T> source, T item)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.With<T>(source, item);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.With instead.")]
        public static ICollection<T> With<T>(this ICollection<T> source, T[] items)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.With<T>(source, items);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.Without instead.")]
        public static ICollection<T> Without<T>(this ICollection<T> source, T item)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.Without<T>(source, item);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.WithMany instead.")]
        public static ICollection<T> WithMany<T>(this ICollection<T> source, IEnumerable<T> items)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.WithMany<T>(source, items);

        [Obsolete("Use global::RzR.Extensions.Domain.Collections.CollectionExtensions.AddToCollectionIfNotExist instead.")]
        public static ICollection<T> AddToCollectionIfNotExist<T>(this ICollection<T> source, T item)
            => global::RzR.Extensions.Domain.Collections.CollectionExtensions.AddToCollectionIfNotExist<T>(source, item);

    }
}
